version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
